// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  //Add Your Web Key
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: '',
    appId: '1:web:',
    messagingSenderId: ',
    projectId: '',
    authDomain: '',
    storageBucket: '',
    measurementId: '',
  );

  //Add Your Android Key
  static const FirebaseOptions android = FirebaseOptions(
    apiKey: '',
    appId: '1:android',
    messagingSenderId: '',
    projectId: '',
    storageBucket: '',
  );

  //Add Your Ios Key
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: '',
    appId: '1::ios',
    messagingSenderId: '',
    projectId: '',
    storageBucket: '',
    iosBundleId: '',
  );

  //Add Your Macos Key
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: ',
    appId: '1::ios:',
    messagingSenderId: '',
    projectId: '',
    storageBucket: '',
    iosBundleId: '',
  );

  //Add Your Windows Key
  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: '',
    appId: '1:web',
    messagingSenderId: '',
    projectId: '',
    authDomain: '',
    storageBucket: '',
    measurementId: '',
  );
}
