// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBLZE9xtbyTvCnaZBbEc2UFbfLNXPMsgow',
    appId: '1:923575873853:web:0550e37e36b91ed18d1554',
    messagingSenderId: '923575873853',
    projectId: 'mcqs-2363f',
    authDomain: 'mcqs-2363f.firebaseapp.com',
    storageBucket: 'mcqs-2363f.firebasestorage.app',
    measurementId: 'G-QS0QG79JXF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBLZE9xtbyTvCnaZBbEc2UFbfLNXPMsgow',
    appId: '1:923575873853:android:0550e37e36b91ed18d1554',
    messagingSenderId: '923575873853',
    projectId: 'mcqs-2363f',
    storageBucket: 'mcqs-2363f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBLZE9xtbyTvCnaZBbEc2UFbfLNXPMsgow',
    appId: '1:923575873853:ios:0550e37e36b91ed18d1554',
    messagingSenderId: '923575873853',
    projectId: 'mcqs-2363f',
    storageBucket: 'mcqs-2363f.firebasestorage.app',
    iosBundleId: 'com.example.cropDamageApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDsFz_Vft7tzxKPGjtYResgqY2IipcO7K4',
    appId: '1:685017752759:ios:4ce0d7e4e2e50722945932',
    messagingSenderId: '685017752759',
    projectId: 'myap-c427b',
    storageBucket: 'myap-c427b.firebasestorage.app',
    iosBundleId: 'com.example.cropDamageApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA6TXTuc9BX5NF40HPvukBP6dpfMJyNZEY',
    appId: '1:685017752759:web:8ed979c93ce85bad945932',
    messagingSenderId: '685017752759',
    projectId: 'myap-c427b',
    authDomain: 'myap-c427b.firebaseapp.com',
    storageBucket: 'myap-c427b.firebasestorage.app',
    measurementId: 'G-624D05GCFN',
  );
}
